# Generated by Django 4.2.6 on 2023-11-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_tasklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
