# Generated by Django 4.2.6 on 2023-11-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasklist',
        ),
    ]
